export default {
  MAIN_PAGE: 'main',
  ABOUT_PAGE: 'about',
  LOGO: 'КАФЕДРА ТЕОРИИ И ПРАКТИКИ КИТАЙСКОГО ЯЗЫКА',
  NAVIGATION: [
    {
      name: 'Преподаватели',
      linkTo: 'teachers',
    },
    {
      name: 'Учебная работа',
      linkTo: 'study',
    },
    {
      name: 'Научная работа',
      linkTo: 'science',
    },
    {
      name: 'Новости',
      linkTo: 'news',
    },
    {
      name: 'Контакты',
      linkTo: 'contacts',
    },
  ],
  COPY_RIGHT: '© 2021 Sych & Trofimov',
  NO_INFO_TEXT: 'Для отображения материалов выберите раздел',
  ABOUT: 'О кафедре',
  COURSE_WORK: 'Курсовые работы',
  GRADUATION_WORK: 'Дипломные работы',
  EXAMPLE: '- Образец задания',
  INSTRUCTIONS: '- Памятка',
  MATERIAL_INFO: '- Информация',
  MASTERS_TITLE: 'Темы магистерских диссертаций',
  UNI_YEARS: [1, 2, 3, 4, 5],
  TEACHER_CONTACTS: {
    name: 'Контакты',
    mobile: 'Телефон',
    email: 'Email',
    website: 'Сайт',
  },
  EDIT_MODAL_LABELS: {
    titleEdit: 'Изменить данные',
    titleAddTeacher: 'Добавить нового преподавателя',
    titleAddNews: 'Добавить новость',
    deleteTeacher: 'Удалить преподавателя',
    deleteNews: 'Удалить новость',
    cancel: 'Отмена',
    save: 'Ok',
    add: 'Создать',
    name: 'ФИО',
    photo: 'Фото',
    position: 'Должность',
    degree: 'Ученая степень',
    subjects: 'Основные предметы',
    about: 'О преподавателе',
    publications: 'Публикации',
    contacts: 'Контакты',
  },
  PUBLICATIONS_LABELS: {
    title: 'Название',
    titleMsg: 'Введите название',
    published: 'Опубликовано',
    publishedMsg: 'Введите место и год публикации',
    url: 'Ссылка',
    urlMsg: 'Введите ссылку на статью',
    addPublication: 'Добавить публикацию',
  },
  CONTACTS_LABELS: {
    addContacts: 'Добавить контакт',
    contactsTitle: 'email / mobile / website',
    incorrectData: 'Впишите верный формат',
  },
  TABLE_COLUMNS_LABELS_TEACHERS: {
    name: 'Имя',
    photo: 'Фото',
    position: 'Должность',
    degree: 'Ученая степень',
    subjects: 'Основные предметы',
    about: 'О преподавателе',
    publications: 'Публикации',
    contacts: 'Контакты',
  },
  TABLE_COLUMNS_LABELS_MATERIALS: {
    sectionName: 'Секция',
    materialsName: 'Материалы',
    firstYear: '1 курс',
    secondYear: '2 курс',
    thirdYear: '3 курс',
    forthYear: '4 курс',
    fifthYear: '5 курс',
    addYear: 'Курс',
    addName: 'Название',
    addSpecialization: 'Специализация',
    specializations: ['(преподавание)', '(перевод)', '(преподавание, перевод)'],
    addNewMaterial: 'Добавить новый материал',
    addPublished: 'Опубликовано (для публикаций и сборников)',
    place: 'Место',
    date: 'Дата',
    url: 'Ссылка',
    author: 'Автор/ы',
  },
  PUBLICATIONS: 'Публикации',
  CONTACTS: 'Контакты',
  DELETE: 'Удалить',
  DELETE_TEACHER_TEXT: 'Удалить преподавателя из системы?',
  DELETE_NEWS_TEXT: 'Удалить новость из системы?',
  ADD_PHOTO_TEXT: 'Добавьте фото!',
  ADD_TEACHER_TEXT: 'Добавить нового преподавателя',
  ADD_NEWS_TEXT: 'Добавить новость',
  UPLOAD_FILE: ['Загрузить файл?', 'Загрузить новый файл?'],
  NO_INFO: '',
};
