export default {
  LOGO: 'КАФЕДРА ТЕОРИИ И ПРАКТИКИ КИТАЙСКОГО ЯЗЫКА',
  NAVIGATION: [
    {
      name: 'Преподаватели',
      linkTo: 'teachers',
    },
    {
      name: 'Учебная работа',
      linkTo: 'study',
    },
    {
      name: 'Научная работа',
      linkTo: 'science',
    },
    {
      name: 'Новости',
      linkTo: 'news',
    },
    {
      name: 'Контакты',
      linkTo: 'contacts',
    },
  ],
  COPY_RIGHT: '© 2021 Sych',
  NO_INFO_TEXT: 'Для отображения материалов выберите раздел',
  ABOUT: 'О кафедре',
  COURSE_WORK: 'Курсовые работы',
  GRADUATION_WORK: 'Дипломные работы',
  EXAMPLE: '- Образец задания',
  INSTRUCTIONS: '- Памятка',
  MATERIAL_INFO: '- Информация',
  MASTERS_TITLE: 'Темы магистерских диссертаций',
  UNI_YEARS: [1, 2, 3, 4, 5],
  CONTACTS: {
    NAME: 'Контакты',
    MOBILE: 'Телефон',
    EMAIL: 'Email',
    WEBSITE: 'Сайт',
  },
  EDIT_MODAL_LABELS: {
    title: 'Изменить данные преподавателя',
    deleteTeacher: 'Удалить преподавателя',
    cancel: 'Отмена',
    save: 'Ok',
    add: 'Создать',
    name: 'ФИО',
    photo: 'Фото',
    position: 'Должность',
    degree: 'Ученая степень',
    subjects: 'Основные предметы',
    about: 'О преподавателе',
    publications: 'Публикации',
    contacts: 'Контакты',
  },
  PUBLICATIONS_LABELS: {
    title: 'Название',
    titleMsg: 'Введите название',
    published: 'Опубликовано',
    publishedMsg: 'Введите место и год публикации',
    url: 'Ссылка',
    urlMsg: 'Введите ссылку на статью',
    addPublication: 'Добавить публикацию',
  },
  CONTACTS_LABELS: {
    addContacts: 'Добавить контакт',
    contactsTitle: 'email / mobile / website',
    incorrectData: 'Впишите верный формат',
  },
  TABLE_COLUMNS_LABELS: {
    name: 'Имя',
    photo: 'Фото',
    position: 'Должность',
    degree: 'Ученая степень',
    subjects: 'Основные предметы',
    about: 'О преподавателе',
    publications: 'Публикации',
    contacts: 'Контакты'
  }
};
