export const SET_LOADING = 'SET_LOADING';
export const SET_PATH = 'SET_PATH';
export const SET_ALL_NEWS = 'SET_ALL_NEWS';
export const SET_CURRENT_NEWS_PAGE = 'SET_CURRENT_NEWS_PAGE';
export const SET_FETCHED_DATA = 'SET_FETCHED_DATA';
export const SET_MODAL_OPEN = 'SET_MODAL_OPEN';
export const SET_TEACHER_INDEX = 'SET_TEACHER_INDEX';
